#!/usr/bin/env bash

# Power/sleep/session options handling via dmenu

case "$(echo -e '⏾ sleep\n exit\nﰇ reboot\n poweroff' | dmenu "$@")" in
    sleep)
        # Lock the session, suspend the screen, then the machine
        # Also, pause any notifications while we're locked
        lock_screen &
        sleep 0.1
        xset dpms force suspend
        systemctl suspend
        ;;

    exit)
        # Kill the window manager
        pkill -TERM dwm
        ;;

    poweroff)
        # Ask the service manager to halt the system and then
        # power off the machine
        systemctl poweroff
        ;;

    reboot)
        # Ask the service manager to halt the system and then
        # restart the machine
        systemctl reboot
        ;;
esac
